apiVersion: v2
name: loki-distributed
description: Helm chart for Grafana Loki in microservices mode
version: 0.48.3
dependencies:
- name: loki-distributed
  version: 0.48.3
  repository: https://grafana.github.io/helm-charts