apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
spec:
  description: project for management of Argo CD itself
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: argo-cd
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/dorroddorrod/demo.git